import type { AttentionItemCode } from '@craftingtable/domain';

/**
 * What each stop is, in the operator's words (R-A5). One short label per code; the item's
 * message says the specifics. Exhaustive, so a new code cannot reach the inbox unnamed.
 */
export const ATTENTION_CODE_LABELS: Readonly<Record<AttentionItemCode, string>> = {
  'service-failure-not-retryable': 'Service failure',
  'service-retries-exhausted': 'Service retries used up',
  'exit-with-open-questions': 'Agent questions',
  'completion-continuations-exhausted': 'Agent did not finish',
  'background-work-unsafe': 'Background work left running',
  'step-incomplete': 'Step incomplete',
  'resolution-needs-guidance': 'Conflict resolution needs guidance',
  'workflow-report-invalid': 'Workflow report invalid',
  'workflow-questions-disagree': 'Workflow report disagrees',
  'shared-decision-required': 'Shared decision required',
  'work-item-questions': 'Work item questions',
  'finalization-needs-input': 'Finalization questions',
  'design-investigation-finished': 'Design investigation finished',
  'design-report-invalid': 'Design report invalid',
  'design-dependency-continuations-exhausted': 'Design dependency unresolved',
  'design-dependency-unsupported': 'Design dependency unsupported',
  'design-planning-conflict': 'Design conflicts with the plan',
  'design-decision-required': 'Design decision required',
  'design-open-questions': 'Design questions',
  'implementation-open-questions': 'Implementation questions',
  'review-open-questions-at-limit': 'Review questions at the round limit',
  'review-open-questions': 'Review questions',
  'finalization-report-rejected': 'Finalization report rejected',
  'polish-assessment-needs-attention': 'Polish assessment',
  'legacy-finalization-retired': 'Retired finalization',
  'scope-review-open-questions': 'Scope review questions',
  'scope-review-recovery': 'Scope review findings',
  'review-needs-attention': 'Review needs attention',
  'restart-session-lost': 'Session lost in a restart',
  'restart-resume': 'Resume after restart',
  'controller-error': 'Controller error',
  'upstream-transition-undeclared': 'Upstream transition undeclared',
  'reassessment-failed': 'Reassessment failed',
  'worktree-inactive': 'Worktree inactive',
  'authority-lost': 'Authority lost',
  'design-recheck-unavailable': 'Design recheck unavailable',
  'step-time-limit': 'Step time limit',
  'service-retry-mismatch': 'Service retry mismatch',
  'scope-review-snapshot-changed': 'Reviewed snapshot changed',
  'review-baseline-changed': 'Review baseline changed',
  'security-reviewer-unassigned': 'Security reviewer unassigned',
  'workflow-obligation': 'Workflow obligation',
  'stage-report-invalid': 'Stage report invalid',
  'finalization-ledger-full': 'Finalization ledger full',
  'plan-change-decision': 'Plan change decision',
  'stage-batch-selection': 'Stage batch selection',
  'stage-review-changes-requested': 'Stage review requested changes',
  'remediation-exhausted': 'Remediation rounds used up',
  'remediation-stalled': 'Remediation stalled',
  'implementation-commit-failed': 'Commit failed',
  'integration-refresh-limit': 'Integration refresh limit',
  'integration-conflict': 'Integration conflict',
  'integration-update-failed': 'Integration update failed',
  'resolution-abandoned': 'Conflict resolution abandoned',
  'merge-approval': 'Merge approval',
  'merge-requirements': 'Merge requirements unmet',
  'final-promotion': 'Final promotion',
  'record-scope-evidence': 'Scope evidence to record',
  'controller-wait': 'Controller wait',
  'scheduling-held': 'Scheduling held',
  'legacy-attention': 'Needs attention',
  'scheduler-error': 'Scheduler error',
  'entry-preparation-failed': 'Item preparation failed',
  'entry-blocked': 'Item blocked',
  'evidence-not-current': 'Evidence no longer current',
  'cycle-needs-attention': 'Cycle needs attention',
  'manual-run-failed': 'Run failed',
  'manual-run-interrupted': 'Run interrupted',
  'manual-review-mergeable': 'Review ready to merge',
  'manual-review-needs-attention': 'Review needs attention',
  'manual-design-questions': 'Design questions',
  'decision-preparation-questions': 'Decision preparation questions',
  'merge-recovery-required': 'Interrupted merge',
  'merge-cleanup-failed': 'Merge cleanup failed',
  'finalization-cleanup-blocked': 'Branch cleanup blocked',
  'amendment-decision': 'Planning amendment',
  'dependency-refresh-resume': 'Refreshed reviews waiting',
  'verification-setup': 'Verification setup',
  'checkpoint-evidence': 'Checkpoint evidence',
  'architecture-decision': 'Architecture decision',
  'plan-acceptance': 'Plan acceptance',
  'storage-pressure': 'Storage',
  'storage-maintenance-failed': 'Storage maintenance',
};
